Add mobile version header
OlichkaKhamuliak/photography-school pull request #2
Opened 2023-09-07 19:03 UTC by Serhii-Kysil

2023-09-07 20:50 UTC, OlichkaKhamuliak requested changes
додай ще в .menu-btn {
padding: 0;
}
забери з цього ж класу cursor: pointer; (він прописаний для усіх кнопок у базових стилях)

2023-09-08 06:45 UTC, Serhii-Kysil commented
Fix .menu-btn{
padding
}
Add tablet and desktop versions

2023-09-08 07:18 UTC, OlichkaKhamuliak requested changes
1. .header-main-button перейменуй на .header-main-link
2. на .logo допиши font-weight: 800;
3. встав всюди де якірні посилання id 
4. заміни на ось це
.logo {
  margin: 17px 0 17px 20px;
  font-size: 23px;
  font-weight: 700;
  letter-spacing: -0.08em;;
}

2023-09-08 07:19 UTC, OlichkaKhamuliak commented
без 2 пункту, нижче написала на що виправити

2023-09-08 07:22 UTC, Serhii-Kysil commented
Додав, зараз запушу

2023-09-08 08:17 UTC, OlichkaKhamuliak requested changes
1. @media only screen and (min-width: 768px) {
  .header-main-link {
   
    min-width: 186px;
    max-height: 60px;

допиши це, простий хейт забери

2. ДОДАЙ 
 @media only screen and (min-width: 1280px) {
  .header-main-link {
        min-width: 238px;
  }
}

3. в тебе немає навігації на лого
Зміни параграф на  <a class="logo link" href="./index.html">Focus.Frame </a>

2023-09-08 08:25 UTC, OlichkaKhamuliak approved these changes
все добре

2023-09-08 08:25 UTC, merged